elasticsearch:
  nodeSets:
    - name: default
      count: 1
      config:
        node.roles: ["master", "data", "ingest"]
      resources:
        limits:
          memory: 2Gi
        requests:
          memory: 1Gi

kibana:
  replicas: 1
  resources:
    limits:
      memory: 1Gi
    requests:
      memory: 500Mi

logstash:
  replicas: 1
  resources:
    limits:
      memory: 2Gi
    requests:
      memory: 1Gi
