apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-apps
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: secret-store-development
    kind: SecretStore
  target:
    name: env-apps
  dataFrom:
  - extract:
      key: apps