apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store-development
spec:
  provider:
    vault:
      # Set your server vault
      server: "https://vault.domain.com"
      path: "development"
      version: "v2"
      # Set Authentication Vault with Token
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"

---

apiVersion: v1
kind: Secret
metadata:
  name: development-secret
stringData:
  token: "hvs.xxxxxxxxxxxxxxxxxx"