replicaCount: 1
image:
  repository: scraping-microservice
  tag: latest
resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"
hpa:
  enabled: true
  targetCPUUtilizationPercentage: 40